services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  OliverKroener\OkAzureLogin\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  OliverKroener\OkAzureLogin\LoginProvider\AzureLoginProvider:
    public: true

  OliverKroener\OkAzureLogin\EventListener\AzureRequestTokenListener:
    tags:
      - name: event.listener
        identifier: 'ok-azure-login/request-token'
        event: TYPO3\CMS\Core\Authentication\Event\BeforeRequestTokenProcessedEvent
